<?php
class ratingConfig
{
	public static $rating = array('body' => array('build_quality',
													'design',
													'haptic',
													'ergonomics'),
									'input' => array('input'),
									'input_method' => array('input_method'),
									'processor' => array('processor'),
									'operatingsystem' => array('operatingsystem'),
									'radio' => array('radio'),
									'fm_transmitter' => array('fm_transmitter'),
									'ports' => array('ports'),
									'data_port' => array('data_port'),
									'secondary_display' => array('secondary_display'),
									'beamer' => array('beamer'),
									'gps_software' => array('gps_software'),
									'time_functions' => array('time_functions'),
									'document_read' => array('document_read'),
									'document_edit' => array('document_edit'),
									'phone_modem' => array('phone_modem'),
									'video_camera' => array('video_quality'),
									'battery' => array('charge_time'),
									'battery_talktime' => array('talktime_gsm',
																'talktime_umts'),
									'battery_runtime_phone' => array('standby_gsm',
																'standby_umts'),
									'battery_runtime_audio' => array('playback_time',
																	'recording_time'),
									'battery_runtime_video' => array('playback_time',
																	'recording_time'),
									'battery_pictures_camera' => array('pictures_without_flash',
																	'pictures_with_flash'),
									'market_information' => array('value_for_money'),
									'internal_memory' => array('size',
																'speed'),
									'ram' => array('size',
																'speed'),
									'extendable_memory' => array('size',
																'speed'),
									'display' => array('display_picture_quality',
													'brightness'),
									'phone' => array('phone_audio_quality',
															'reception'),
									'wireless' => array('wireless_support'),
									'call_notification' => array('volume',
																'versatility'),
									'contact_management' => array('versatility',
																'usability'),
									'input' => array('key_press',
													'usability'),
									'operating_system' => array('operating_speed',
																'versatility',
																'extendable_software',
																'mutlitasking'),
									'audio_recording' => array('recording_quality'),
									'radio' => array('reception',
													'functionality'),
									'camera' => array('picture_quality',
													'speed'),
									'picture_display' => array('picture_quality',
															'loading_time'),
									'flash' => array('range',
													'brightness'),
									'video_recording' => array('video_quality'),
									'video_playback' => array('video_quality'),
									'television' => array('tv_quality'),
									'audio_player' => array('music_audio_quality'),
									'radiation' => array('radiation_level'),
									'speaker' => array('speaker_quality',
														'maximum_volume'),
									'gsm_runtime' => array('gsm_runtime'),
									'umts_runtime' => array('umts_runtime'),
									'gps' => array('satfix'),
									'nav_routing' => array('computing_time',
															'quality_of_route'),
									'nav_output' => array('speech_quality',
														'momemt_of_announcement'),
									'browser' => array('browser_functionality'),
									'sync' => array('sync_functions'),
									'accessories' => array('included_delivery'),
									'sms' => array('sms_function'),
									'mms' => array('mms_function'),
									'email' => array('email_function'),
									'instant_messenger' => array('instant_messenger_function'),
									'contacts' => array('contact_management'),
									'calendar' => array('calendar_usability'),
									'notes' => array('versatility',
													'usability'),
									'calculator' => array('usability',
														'quality'),
									'personalization' => array('versatility'));
	
	/*
	public static $rating = array('body' => array('build_quality',
													'design',
													'haptic',
													'ergonomics'),
									'battery' => array('charge_time'),
									'battery_talktime' => array('talktime_gsm',
																'talktime_umts'),
									'battery_runtime_phone' => array('standby_gsm',
																'standby_umts'),
									'battery_runtime_audio' => array('playback_time',
																	'recording_time'),
									'battery_runtime_video' => array('playback_time',
																	'recording_time'),
									'battery_pictures_camera' => array('pictures_without_flash',
																	'pictures_with_flash'),
									'market_information' => array('value_for_money'),
									'internal_memory' => array('size',
																'speed'),
									'ram' => array('size',
																'speed'),
									'extendable_memory' => array('size',
																'speed'),
									'display' => array('display_picture_quality',
													'brightness'),
									'phone' => array('phone_audio_quality',
															'reception'),
									'wireless' => array('wireless_support'),
									'call_notification' => array('volume',
																'versatility'),
									'contact_management' => array('versatility',
																'usability'),
									'input' => array('key_press',
													'usability'),
									'operating_system' => array('operating_speed',
																'versatility',
																'extendable_software',
																'mutlitasking'),
									'audio_recording' => array('recording_quality'),
									'radio' => array('reception',
													'functionality'),
									'camera' => array('picture_quality',
													'speed'),
									'picture_display' => array('picture_quality',
															'loading_time'),
									'flash' => array('range',
													'brightness'),
									'video_recording' => array('video_quality'),
									'video_playback' => array('video_quality'),
									'television' => array('tv_quality'),
									'audio_player' => array('music_audio_quality'),
									'radiation' => array('radiation_level'),
									'speaker' => array('speaker_quality',
														'maximum_volume'),
									'battery_runtime' => array('runtime_music_playback',
																'runtime_video_playback'),
									'gps' => array('satfix'),
									'nav_routing' => array('computing_time',
															'quality_of_route'),
									'nav_output' => array('speech_quality',
														'momemt_of_announcement'),
									'browser' => array('browser_functionality'),
									'sync' => array('sync_functions'),
									'accessories' => array('included_delivery'),
									'sms' => array('sms_function'),
									'mms' => array('mms_function'),
									'email' => array('email_function'),
									'instant_messenger' => array('instant_messenger_function'),
									'contacts' => array('contact_management'),
									'calendar' => array('calendar_usability'),
									'notes' => array('versatility',
													'usability'),
									'calculator' => array('usability',
														'quality'),
									'personalization' => array('versatility'));
									*/
}
?>